### ISSUE TITLE
HowLongToBeat Intgration

### ISSUE THREAD

**Issue by d7eeem** [CMorooney/obsidian-game-search-plugin#10]
Is there any possibility of adding it to the plugin?

**Comment by CMorooney** [comment]
hm, HowLongToBeat does not have a public API as far as I know so any existing or new solutions would have to be web scraped -- that's a little brittle for my taste and available maintenance time.

@d7eeem is there a specific feature that exists on HowLongToBeat that you want to see added here? or is it just that you already have a backlog on there that you would like to import or synchronize with? perhaps there's another way we can implement what you're looking for

**Comment by d7eeem** [comment]
I just wanted to get the time of each game in the database. and i am learning JS at the moment and it's early days for me to bite into it. 

and i found this project which is a  "simple wrapper API".

https://github.com/ckatzorke/howlongtobeat

**Comment by CMorooney** [comment]
> and i found this project which is a "simple wrapper API".
> https://github.com/ckatzorke/howlongtobeat

[it looks like this is still just scraping the HTML](https://github.com/ckatzorke/howlongtobeat/blob/master/src/main/howlongtobeat.ts#L103). This is not something I'm looking to maintain or add a dependency for at the moment.

BUT if you're learning JS and are looking for a project you are interested in to learn more, I think you could reasonably fork this repo and swap the provider from RAWG to HLTB. The code is written in typescript so if you haven't seen that before it might look a _little_ strange but in the end it'll probably help 😅

aside: I hear the HLTB uses Steam data occasionally for playtime info...maybe someday in the near future we could add an optional Steam integration here, though that's obviously a bit platform restrictive
