### ISSUE TITLE
Error: request failed, status 401

### ISSUE THREAD

**Issue by gbrlsfernandez** [CMorooney/obsidian-game-search-plugin#11]
Hi there! I'm trying to set the plugin up but I'm encountering the error in the title.

Steps:
1. Get RAWG API Key from https://rawg.io/@username_here/apikey
2. Set the RAWG API Key, Folder, File Name, and Template in General Settings of the Plugin
3. Execute command Game Search: Create new game note
4. Type a game keyword, e.g. Sekiro
5. Click Search button

Result:
1. Error: request failed, status 401

Do I need to use a different API Key or is this currently a bug?

Thank you!

**Comment by CMorooney** [comment]
@gbrlsfernandez that's odd -- I quickly tested on my end and I don't get an `Unauthorized` error. Are you certain that the key you entered is accurate and valid?

**Comment by gbrlsfernandez** [comment]
@CMorooney I got it working after I tried it again just recently. Must've been a caching issue since I ran the command right after getting a fresh API Key or might've been just my internet at the time lol. Thanks for confirming though! Cheers

**Comment by danielo515** [comment]
I am facing this exact problem following the same steps. Will let it settle

**Comment by CMorooney** [comment]
> I am facing this exact problem following the same steps. Will let it settle 

Hi @danielo515 did the issue resolve itself?

**Comment by danielo515** [comment]
Just checked. Yes, it did.
They should mention the API key takes some time to activate.
Thanks
