### ISSUE TITLE
Ability to display array object as list instead of a comma separated text

### ISSUE THREAD

**Issue by alessdangelo** [CMorooney/obsidian-game-search-plugin#12]
Hello! I was wondering why the arrays object uses commas by default, as having it using a list format could make it easier to use on obsidian ? Would that be something that can be added ? Thank you for your time

**Comment by alessdangelo** [comment]
Nevermind it was an issue on my end.. but correctly adding brackets (ex: [{{platforms}}]) displays it as a list
<img width="476" alt="image" src="https://github.com/CMorooney/obsidian-game-search-plugin/assets/61836900/fe041a03-65b2-4d2d-a3c9-0659410ac6a0">

**Comment by CMorooney** [comment]
Appreciate the follow up, glad you got it sorted
