### ISSUE TITLE
Tags variable isn't being correctly serialized

### ISSUE THREAD

**Issue by S1rDev10us** [CMorooney/obsidian-game-search-plugin#13]
# Steps

- Setup plugin
- Connect API key
- Create a template file with the tags variable in it
- Set template in settings
- Create new ~~book~~ *game* note

# Result

![image](https://github.com/CMorooney/obsidian-game-search-plugin/assets/90798437/e7e0c48e-8181-4c22-b453-2c8137e5cb69)

**Comment by CMorooney** [comment]
oops -- I missed this on review but just fwiw these were necessary changes
https://github.com/CMorooney/obsidian-game-search-plugin/commit/36f98aa574e5f5580d3b91212c41de7c3b9f1dfd
