### ISSUE TITLE
How to fix this error message??

### ISSUE THREAD

**Issue by OPEN1004MIND** [CMorooney/obsidian-game-search-plugin#18]
When I enter the name of any game in the Search Game field, it doesn't work with an error message like below.

I got the API key and entered it.

"Error: Request failed, status 401" 

I tested it by typing https://api.rawg.io/api/platforms?key={my API key}
and it works.

**Comment by CMorooney** [comment]
Hi @OPEN1004MIND thanks for opening an issue --

This has been opened a number of times, it seems that the RAWG API takes some time to accept a newly generated API key and that the issue resolves itself after some time

here's the main issue that was closed over this:
https://github.com/CMorooney/obsidian-game-search-plugin/issues/11

has your error resolved itself or is it still occurring?

**Comment by CMorooney** [comment]
@OPEN1004MIND that thumbs up reaction.... is the issue resolved?

**Comment by CMorooney** [comment]
closing

**Comment by OPEN1004MIND** [comment]
Thank you
Working fine !
