### ISSUE TITLE
Creating a new game note gives error

### ISSUE THREAD

**Issue by kamransoomro84** [CMorooney/obsidian-game-search-plugin#20]
**Describe the bug**

Creating a new game note gives the following error:

![image](https://github.com/CMorooney/obsidian-game-search-plugin/assets/4132530/b84ae81e-505b-40ea-aa08-5357179251cf)

**To Reproduce**

1. Create a new game note. 
2. Search for a game.
3. Select a game to create a new note. 

**Expected behavior**

Mew note should be created with the provided template.

**Comment by CMorooney** [comment]
whoooops sorry about that @kamransoomro84 , thanks a lot for opening an issue!

should be addressed in [0.2.1](https://github.com/CMorooney/obsidian-game-search-plugin/releases/tag/0.2.1) please let me know if you continue to have issues!

**Comment by kamransoomro84** [comment]
Thanks. It seems to be working now!
