### ISSUE TITLE
`esrb_rating` renders as `[object Object]`

### ISSUE THREAD

**Issue by breakid** [CMorooney/obsidian-game-search-plugin#46]
**Describe the bug**

The `{{esrb_rating}}` template variable is replace with `[object Object]`.

**To Reproduce**

1. Add `esrb_rating: {{esrb_rating}}` to the metadata portion of your template
2. Generate a note for a game with an ESRB rating (e.g., `Aegis Defenders (2018)`)
3. The note should contain:

    ```
    esrb_rating: [object Object]
    ```

**Expected behavior**

The `name` attribute of the `RAWGESRBRating` object should be returned

**Comment by CMorooney** [comment]
released your fix in 0.2.13 -- thanks!
