### ISSUE TITLE
Create a way to "Update All" Game notes currently made.

### ISSUE THREAD

**Issue by Negative-light** [CMorooney/obsidian-game-search-plugin#6]
# Premise

Add a command to Update all of the current games to the latest template. This allows the user to easily both change the template and incorporate new data.
This allows us to plan out different sections and steadily incorporate parts of the API. Particularly I would like this for the sake of the new Publisher feature and I would also like to more easily add the ESRB ratings.

**Comment by CMorooney** [comment]
@Negative-light This makes sense to me -- at the moment i can't think of a guaranteed way to replace current game files without potentially blowing away any content that was not generated from the template (depending on how the user has mingled their own content with their templated content).

I may just include a warning to back up any important notes before updating any game notes unless you had a different thought!

**Comment by CMorooney** [comment]
> @Negative-light This makes sense to me -- at the moment i can't think of a guaranteed way to replace current game files without potentially blowing away any content that was not generated from the template (depending on how the user has mingled their own content with their templated content).
> 
> I may just include a warning to back up any important notes before updating any game notes unless you had a different thought!

Or i could just try and ONLY replace the metadata 🤔

**Comment by Negative-light** [comment]
I kinda feel that might need some config possibly. Maybe add a toggle in the settings.
I personally think a full rewrite makes sense as I usually have updated the template.
The usability of this feature is that one doesn't have to manually redo **all** of the games that they have pulled in.
An alternative would be to allow users to provide a link or some kind of id that you could easily get from the game's name and have them in a file and pull all of that in one go. I feel that is a separate feature and could be useful possibly its own issue even

**Comment by CMorooney** [comment]
@Negative-light I'm going to sleep on this to make sure I didn't overthink anything but here's a PR with a full-file-replace options I guess that's a good first step!

**Comment by CMorooney** [comment]
@Negative-light [0.1.5] has been released and can be updated to through obsidian plugin manager.
let me know if you have other issues or this doesn't work for you!
https://github.com/CMorooney/obsidian-game-search-plugin/releases/tag/0.1.5

**Comment by Negative-light** [comment]
Love it thanks
