### ISSUE TITLE
ribbon icon missing

### ISSUE THREAD

**Issue by alessdangelo** [CMorooney/obsidian-game-search-plugin#8]
Hello !  There is no icon on my end, is there an icon yet ? 

<img width="167" alt="image" src="https://github.com/CMorooney/obsidian-game-search-plugin/assets/61836900/dc96ff98-f9f2-465f-8cf9-dd4c959edda8">

**Comment by CMorooney** [comment]
Hi @alessdangelo -- thanks for opening an issue!
should be solved in the [latest release](https://github.com/CMorooney/obsidian-game-search-plugin/releases/tag/0.1.6) that should have gone out now
